[project]
name = "bitbucket-migration"
version = "0.2.0"
description = "Scripts to assist with the migration of a Bitbucket git repository to GitHub."
authors = [
    { name = "FKloosterman", email = "devfakl@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "python-dotenv>=1.0.0",
    "cryptography>=43.0.0",
    "dotenv>=0.9.9",
]

[build-system]
    requires = ["setuptools>=61.0"]
    build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["bitbucket_migration*"]

[dependency-groups]
dev = [
    "twine>=6.2.0",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.22",
    "pymdown-extensions>=10.16.1",
]

[project.scripts]
    migrate_bitbucket_to_github = "bitbucket_migration.migrate_bitbucket_to_github:main"
    bb2gh = "bitbucket_migration.migrate_bitbucket_to_github:main"
