name: Publish Docs to GitHub Pages (uv)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write      # Needed to push to gh-pages
  pages: write         # (optional) Needed for new Pages builds
  id-token: write      # (optional) For OpenID authentication if required

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync --group docs

      - name: Build docs
        run: uv run mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
