name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to publish to (pypi or testpypi)'
        required: true
        default: 'pypi'
        type: choice
        options:
          - pypi
          - testpypi

permissions:
  contents: read
  id-token: write  # OIDC for trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment == 'testpypi' && 'testpypi' || 'pypi' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install build dependencies
        run: uv sync --group dev

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        if: inputs.environment == 'pypi' || github.event_name == 'release'
        env:
          UV_PUBLISH_URL: ${{ inputs.environment == 'testpypi' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
        run: uv publish --trusted-publishing always

      - name: Publish to TestPyPI
        if: inputs.environment == 'testpypi' && github.event_name == 'workflow_dispatch'
        env:
          UV_PUBLISH_URL: https://test.pypi.org/legacy/
        run: uv publish --trusted-publishing always